# Generated by Django 6.0.2 on 2026-02-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaar',
            name='updated_at',
        ),
    ]
