# Generated by Django 6.0.1 on 2026-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFC_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfc_user',
            name='contact',
            field=models.CharField(default='8839125240', max_length=10),
            preserve_default=False,
        ),
    ]
