# Generated by Django 6.0.1 on 2026-02-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
